spring:
  application:
    name: hestia
  datasource:
    url: "${HESTIA_POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres&ApplicationName=hestia}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      idle-timeout: 30000

logging:
  level:
    io.github.aloussase: DEBUG

dashboard:
  page:
    title: Home Lab
  panels:
    cmds:
      - "figlet 'Home Lab'"
    images:
      - 'https://i.giphy.com/sULKEgDMX8LcI.webp'
    docker:
      enabled: true
    postgres:
      enabled: true
